# Generated by Django 4.2.1 on 2023-05-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=4, max_length=4
            ),
        ),
    ]
